### Exercises: NumPy

##### Q1) Create a null vector (all zeros) of size 10 and set it to the variable called 'Z'.

In [2]:
import numpy as np

In [4]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


##### Q2) Create a 1D array of numbers from 0 to 0 and set it to the variable called 'arr'.

In [5]:
arr = np.arange(0, 10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


##### Q3) Create a 3x3x3 array with random values and set it to the variable called 'arr'.

In [9]:
arr = np.random.random((3, 3, 3))
print(arr)

[[[0.83110017 0.8764977  0.91410703]
  [0.82674089 0.15729493 0.40597222]
  [0.11661507 0.5472147  0.90056557]]

 [[0.12912506 0.43360449 0.09618953]
  [0.13054315 0.32608504 0.02722476]
  [0.49348489 0.32870957 0.52097943]]

 [[0.2263314  0.63815581 0.58620255]
  [0.3939123  0.87677569 0.39387127]
  [0.1616156  0.65418184 0.76847954]]]


##### Q4) Create a 10x10 array with random values called 'arr4'. Find its minimum and maximum values and set them in the variables called 'min_val' and 'max_val' respectively. 

In [11]:
arr4 = np.random.random((10, 10))
min_val = arr4.min()
max_val = arr4.max()

print(min_val)
print(max_val)

0.008614241081679741
0.9964381795355284


##### Q5) First create a 1D array with numbers from 1 to 9 and then convert it into a 3x3 grid. Store the final answer in a variable called 'grid'.

In [13]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##### Q6) Replace the maximum value in the given vector 'arr6' with -1. 

In [14]:
arr6 = np.arange(10)
arr6[arr6.argmax()] = -1
print(arr6)

[ 0  1  2  3  4  5  6  7  8 -1]


##### Q7) Reverse the rows of the given 2D array, 'arr7'.

In [15]:
arr7 = np.arange(9).reshape((3, 3))
arr7 = arr7[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

##### Q8) Subtract the mean of each row of the given 2D array, 'arr8', from the values in the array. Set the updated array in 'transformed_arr8'.

In [17]:
arr8 = np.random.rand(3, 10)
transformed_arr8 = arr8 - arr8.mean(axis = 1, keepdims = True)
print(transformed_arr8)

[[-3.59497776e-01  3.20579040e-01 -2.46166358e-01 -3.74137576e-01
  -3.49945764e-01 -1.44582928e-01  3.76139670e-01  3.28891989e-01
   2.53940656e-01  1.94779046e-01]
 [-2.43145726e-01 -6.23959580e-02 -2.27210964e-01  2.89766280e-01
  -1.92105829e-01 -2.54991101e-01  3.88433105e-01 -3.41804768e-01
   4.61322811e-01  1.82132149e-01]
 [-1.02995436e-01  2.17068835e-01  1.27064526e-02  3.87643107e-02
  -2.85165670e-01  6.02451773e-02  3.22162255e-01 -1.51725668e-01
  -1.11259455e-01  1.99199514e-04]]
